# Name your project! Project names should contain only lowercase characters
# and underscores.
name: 'nyc_taxi_dbt'
version: '1.0.0'
config-version: 2

# This setting specifies which config-version apply to project-level files.
profile: 'nyc_taxi_dbt'

# These configurations specify where dbt should look for various files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configure-models

models:
  nyc_taxi_dbt:
    staging:
      +materialized: view